cleaner user prompt fucntion to install packages/flatpaks

diff --git a/distro_setup b/distro_setup
--- a/distro_setup
+++ b/distro_setup
@@ -256,21 +256,40 @@ install_packages() {
         fi
     done
     
+
+    if [[ "${#to_install[@]}" -gt 0 ]]; then
+        echo "The following Flatpak packages will be installed: ${to_install[*]}"
+        echo -e "${BOLD_MAGENTA}You have 15 seconds to respond. Press 'y/Y' to proceed, or any other key to abort.${NC}"
+        # Read user input with a timeout
+        
+        read -t 15 -n 1 -r -s -p "Proceed? (y/Y/wait): " choice; then
+        echo
+        if [[ ! "$choice" =~ [yY] && -n "$choice" ]]; then
+            echo "Skipped."
+            return
+        fi
+        
+        flatpak install -y --noninteractive flathub "${to_install[@]}"
+    fi
+
+
+
+
     if [[ "${#to_install[@]}" -gt 0 ]]; then
         echo "The following packages will be installed: ${to_install[*]}"
         echo -e "${BOLD_MAGENTA}You have 15 seconds to respond. Press 'y/Y' to proceed, or any other key to abort.${NC}"
+        
         # Read user input with a timeout
-        read -t 15 -n 1 -p "Proceed? (y/Y/wait): " choice
-        case "$choice" in
-            y|Y|"")
-                sudo $package_manager install -y "${to_install[@]}" #> /dev/null
-                ;;
-            *)
-                echo -e "Packages installations aborted. Either perform a manual check\n or re-run the script and allow installing the required packages."
-                echo "Exiting..."
-                exit 1
-                ;;
-        esac
+        read -t 15 -n 1 -r -p "Proceed? (y/Y/wait): " choice; then
+        echo
+        
+        if [[ ! "$choice" =~ [yY] && -n "$choice" ]]; then
+            echo -e "Packages installations aborted. Either perform a manual check\n or re-run the script and allow installing the required packages."
+            echo "Exiting..."
+            exit 1
+        fi
+        
+        sudo $package_manager install -y "${to_install[@]}" #> /dev/null
     fi
 }
 
@@ -503,20 +522,19 @@ install_flatpak_packages() {
 	    fi
     done
 
-
     if [[ "${#to_install[@]}" -gt 0 ]]; then
         echo "The following Flatpak packages will be installed: ${to_install[*]}"
         echo -e "${BOLD_MAGENTA}You have 15 seconds to respond. Press 'y/Y' to proceed, or any other key to abort.${NC}"
+        
         # Read user input with a timeout
-        read -t 15 -n 1 -p "Proceed? (y/Y/wait): " choice
-        case "$choice" in
-            y|Y|"")
-                flatpak install -y --noninteractive flathub "${to_install[@]}"
-                ;;
-            *)
-                echo "Skipped."
-                ;;
-        esac
+        read -t 15 -n 1 -r -p "Proceed? (y/Y/wait): " choice; then
+        echo
+        if [[ ! "$choice" =~ [yY] && -n "$choice" ]]; then
+            echo "Skipped."
+            return
+        fi
+        
+        flatpak install -y --noninteractive flathub "${to_install[@]}"
     fi
 }
 
@@ -787,6 +805,7 @@ ask_user_confirmation() {
     local response
 
     read -p "$prompt (y/n): " response
+    echo
     case $response in
         [Yy]* ) return 0;;
         [Nn]* ) return 1;;
@@ -833,6 +852,7 @@ main(){
         echo "(*) - if not exists/set/configured"
 
         read -p "Enter the option/s you would like to perform (1, 2, 3, 4, 5, 6, 7, 8, 9 or q): " selection
+        echo
         case "$selection" in
             1)
                 if ! ask_user_confirmation "You selected to perform a minimal system setup. Would you like to proceed?"; then
@@ -917,7 +937,7 @@ main(){
         echo "-------------------------------------------------------------------"
 
         echo -e "You are advised to READ the above summary before continuing, pay attention to the BOLD_MAGENTA ones.\nYou can also find them by scrolling up if you would like to keep performing actions."
-        read -p "Press Enter to continue..."
+        read -p -s "Press Enter to continue..."
     done
 }
 
